### ISSUE TITLE
Command Option Issue

### ISSUE THREAD

**Issue by seep** [bustardcelly/grunt-forever#6]
I'm having some trouble specifying the `command` option. Here's my configuration for `grunt-forever` (in CoffeeScript).

```
# grunt-forever
forever:
  options:
    index:   'bin/bootstrap.coffee'
    command: 'coffee'
```

Unfortunately, the server doesn't start (I've tested the script with `coffee` directly, as well as `forever start -c 'coffee' bin/bootstrap.coffee` and both succeed). I'm inclined to think it's an issue with `grunt-forever` because checking `forever list` after running grunt shows the process command as `/usr/local/bin/node`.

Any ideas why this might not be working?
