### ISSUE TITLE
forever:start apparently not working

### ISSUE THREAD

**Issue by doughsay** [bustardcelly/grunt-forever#9]
Sorry I can't be more detailed, but there are no errors thrown and no logs to speak of.  The forever start task just doesn't work.  It appears to work:

```
Attempting to start app.coffee as daemon.
Logs can be found at /path/to/log.

Done, without errors.
```

But `forever list` shows no running processes.

The relevant Gruntfile snippet is this:

```
forever:
  options:
    index: 'app.coffee'
    logDir: 'log'
    command: './node_modules/.bin/coffee'
```
